config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'companies#index'

  concern :favoritable do
    member do
      patch :add_to_favorites
      patch :remove_from_favorites
    end
  end

  resources :companies, only: [:index, :show], concerns: :favoritable
  resources :people, only: [], concerns: :favoritable

  get :favorites, to: 'favorites#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  attr_reader :user

  def initialize(user)
    @user = user
    if user
      user_abilities
    else
      guest_abilities
    end
  end

  private

  def guest_abilities
  end

  def user_abilities
    alias_action :add_to_favorites, :remove_from_favorites, to: :favorites

    can :read, Company
    can :favorites, favoritables
    can :read, Favorite
  end

  def favoritables
    [Company, Person]
  end
end

app/models/company.rb
class Company < ActiveRecord::Base
  include Favoritable

  has_many :people, dependent: :restrict_with_exception

  FIELD_FORMAT = {
    country_code: /\A[a-z]{2}\z/i
  }

  validates :country_code, presence: true, format: FIELD_FORMAT[:country_code]
  validates :name, presence: true
end

app/models/concerns/authorable.rb
module Authorable
  extend ActiveSupport::Concern

  included do
    belongs_to :user
    validates :user, presence: true
    alias_attribute :author, :user
  end
end

app/models/concerns/favoritable.rb
module Favoritable
  extend ActiveSupport::Concern

  included do
    has_many :favorites, as: :favoritable, dependent: :destroy
  end

  def add_to_favorites(user)
    favorites.create(user: user)
    self
  end

  def remove_from_favorites(user)
    favorites.where(user: user).delete_all
    self
  end

  def favorited_by?(user)
    favorites.where(user: user).any?
  end
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  include Authorable

  belongs_to :favoritable, polymorphic: true
  validates :user_id, uniqueness: { scope: [:favoritable_id, :favoritable_type] }

  default_scope { order(created_at: :desc) }
end

app/models/person.rb
class Person < ActiveRecord::Base
  include Favoritable

  belongs_to :company, required: true

  validates :first_name, :last_name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :favorites, dependent: :destroy
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    if request.xhr?
      if signed_in?
        action = exception.action
        resource = exception.subject.class.to_s.pluralize
        error_message = "You don't have permission to #{action} #{resource}"
        render status: :forbidden, text: error_message
      else
        error_message = "You must log in first"
        render status: :unauthorized, text: error_message
      end
    else
      render status: :forbidden, file: "public/403.html"
    end
  end

  check_authorization unless: :devise_controller?
end

app/controllers/application_thin_controller.rb
require "application_responder"

class ApplicationThinController < ApplicationController
  self.responder = ApplicationResponder
  respond_to :html

  private

  # before_action :load_resource, only: [:show, :update, :destroy, ...]
  # :include_resources may be overriden in controller
  def load_resource
    record = resource_model.includes(include_resources).find(params[:id])
    instance_variable_set("@#{resource_name}", record)
  end

  # :permit_attributes must be overriden in controller
  def resource_params
    strong_params = params.require(resource_name.to_sym).permit(*permit_attributes)
    strong_params.merge(user_id: current_user.id) if user_signed_in?
  end

  def resource_model
    @resource_model ||= controller_name.classify.constantize
  end

  def resource_name
    @resource_name ||= controller_name.singularize
  end

  def resource
    @resource ||= instance_variable_get("@#{resource_name}")
  end

  def include_resources
    []
  end

  def permit_attributes
    []
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationThinController
  include FavoritableController

  before_action :authenticate_user!
  before_action :load_resource, only: [:show]
  authorize_resource

  def index
    @companies = Company.all
    respond_with @companies
  end

  def show
    respond_with @company
  end

  private

  def include_resources
    [:people]
  end
end

app/controllers/concerns/favoritable_controller.rb
module FavoritableController
  extend ActiveSupport::Concern

  included do
    before_action :load_favoritable_resource, only: [:add_to_favorites, :remove_from_favorites]
  end

  def add_to_favorites
    authorize! :favorites, @favoritable
    @favoritable.add_to_favorites current_user
    render_favorites
  end

  def remove_from_favorites
    authorize! :favorites, @favoritable
    @favoritable.remove_from_favorites current_user
    render_favorites
  end

  private

  def load_favoritable_resource
    @favoritable = controller_name.classify.constantize.find(params[:id])
  end

  def render_favorites
    render 'favorites/update'
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationThinController
  before_action :authenticate_user!
  authorize_resource

  def index
    @favorites = current_user.favorites
    respond_with @favorites
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationThinController
  include FavoritableController

  before_action :authenticate_user!
  authorize_resource
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/companies/_company.html.slim
- country_name = Country.find_country_by_alpha2(company.country_code).name

= div_for company
  span
    = link_to company.name, company_path(company)
  span
    =< "(#{company.country_code} - #{country_name})"
  = render 'favorites/show', favoritable: company

app/views/companies/_index_record.html.slim
- country_name = Country.find_country_by_alpha2(company.country_code).name

= div_for company
  span
    = link_to company.name, company_path(company)
  span
    =< "(#{company.country_code} - #{country_name})"
  = render 'favorites/show', favoritable: company

app/views/companies/index.html.slim
- if can? :read, Favorite
  div
    = link_to 'My favorites', favorites_path

h1 Companies

.companies
  = render @companies

app/views/companies/show.html.slim
- company = @company
- country_name = Country.find_country_by_alpha2(company.country_code).name

- if can? :read, Company
  div
    = link_to 'All companies', companies_path

= div_for company
  h1
    = "Company: #{company.name}"
  p
    span = "#{company.country_code} - #{country_name}"
    = render 'favorites/show', favoritable: company
  h2
    | People
  p
    = render 'people/list', company: company

app/views/favorites/_show.html.slim
- if can? :favorites, favoritable

  - if favoritable.favorited_by? current_user
    =< link_to '★', \
    polymorphic_path([:remove_from_favorites, favoritable]), \
    id: "favorites_#{ dom_id favoritable }", \
    class: "favorite", \
    remote: true, method: :patch

  - else
    =< link_to '☆', \
    polymorphic_path([:add_to_favorites, favoritable]), \
    id: "favorites_#{ dom_id favoritable }", \
    class: "favorite", \
    remote: true, method: :patch

app/views/favorites/index.html.slim
- if can? :read, Company
  div
    = link_to 'All companies', companies_path

h1 My favorites

- @favorites.each do |favorite|
  - favoritable = favorite.favoritable

  = render favoritable

app/views/favorites/update.js.erb
$('#favorites_<%= dom_id @favoritable %>').replaceWith('<%= j render 'favorites/show', favoritable: @favoritable %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ArsVision</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/people/_list.html.slim
= div_for company, :people, class: :people
  = render company.people, company: company

app/views/people/_person.html.slim
= div_for person
  span
    = person.first_name
  span
    =< person.last_name
  = render 'favorites/show', favoritable: person